### ISSUE TITLE
chatbot example issue

### ISSUE THREAD

**Issue by gpengzhi** [asyml/forte#110]
I run the chatbot example on my laptop (CPU).

```
Pengzhis-MacBook-Pro:chatbot pengzhi.gao$ python chatbot_example.py
Traceback (most recent call last):
  File "chatbot_example.py", line 110, in <module>
    main()
  File "chatbot_example.py", line 49, in main
    processor=SearchProcessor(), config=config.indexer)
  File "/Users/pengzhi.gao/Desktop/my_git/forte/forte/processors/search_processor.py", line 39, in __init__
    "device": "gpu0"
  File "/Users/pengzhi.gao/Desktop/my_git/forte/forte/indexers/indexers.py", line 87, in __init__
    index_class = utils.get_class(index_type, module_paths=["faiss"])
  File "/Users/pengzhi.gao/Desktop/my_git/forte/forte/utils.py", line 88, in get_class
    "Class not found in {}: {}".format(module_paths, class_name))
ValueError: Class not found in ['faiss']: GpuIndexFlatIP
```

**Comment by hunterhector** [comment]
This is a dependency issue (missing faiss). Need to update the example README to add this additional dependency.

**Comment by munachisonwadike** [comment]
Greetings!  👋🏾
Actually for me, even when I installed faiss using the instructions in the readme (i.e using `pip install faiss-gpu` and `pip install src/faiss`), I still get the same error..
If we have a bit of a look at the screenshot below, we see it appears the chatbot code actually tries to access the `fortex.faiss` before throwing the error 
What would you suggest?
Warm regards,
![image](https://user-images.githubusercontent.com/22077758/161864571-5ba99a4e-e434-4820-96e4-47e062a570a8.png)

**Comment by hunterhector** [comment]
Is faiss-gpu installed? You can test faiss gpu installation following their documentation: https://github.com/facebookresearch/faiss/blob/main/INSTALL.md#real-life-test-on-gpu
