### ISSUE TITLE
StanfordNLP sentence segmenter bug

### ISSUE THREAD

**Issue by atif93** [asyml/forte#152]
While trying to find sentence boundaries, the technique to find the sentence ending can fail.  
We are using `find` which gives the first occurrence of a word in a sentence. This will definitely fail when there are 2 duplicate words in a sentence.

https://github.com/asyml/forte/blob/master/forte/processors/stanfordnlp_processor.py#L72

**Comment by hunterhector** [comment]
Thanks for spotting this. Let's try to add the failure cases to tests, and come up with a universal solution for such cases.

**Comment by hunterhector** [comment]
Will close this and solve problems using a universal solution https://github.com/asyml/forte/issues/86
