### ISSUE TITLE
Create Reader for Open IE Task (OIE 2016)

### ISSUE THREAD

**Issue by hunterhector** [asyml/forte#230]
**Is your feature request related to a problem? Please describe.**
This feature will create a simple reader to read an Open IE dataset. Find the OIE 2016 task:
https://github.com/gabrielStanovsky/oie-benchmark

**Describe the solution you'd like**
1. Create an appropriate field for this dataset using the ontology.
1. Read in data as Forte format.
(Some readers examples are here: https://github.com/asyml/forte/tree/master/forte/data/readers). You will likely to use the Relation Link object defined here (https://github.com/asyml/forte/blob/master/ft/onto/base_ontology.py#L285).

1. Write test cases for this reader. Here is an example:
https://github.com/asyml/forte/blob/master/tests/forte/data/readers/race_multi_choice_qa_reader_test.py

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by jasonyanwenl** [comment]
Hi Hector, here are my several questions based on your requirement. Thanks in advance!

> Create an appropriate field for this dataset using the ontology.

* Q1: What do you mean by creating a field for this dataset? Could you elaborate a bit more?

* Q2: The following is one sample row I extracted from the OIE dataset that I found. Just would like to check if the OIE dataset I found is correct?
```
# Format: Row
[SENTENCE  PREDICATE   ARG1    ARG2    ....]
# Sample row
QVC Network Inc. said it completed its acquisition of CVN Cos. for about $ 423 million .    said    said    QVC Network Inc.    it completed its acquisition of CVN Cos. for about $ 423 million .
```

> Read in data as Forte format.
  
* Q3: based on the OIE dataset, I probably will create all the following entries for oie reader. Are those correct?
```
Document("<the entire document (all rows like the above in the file)>")
Sentence("<the entire above sentence>")
PredicateMention("said")
PredicateArgument("said")
PredicateArgument("QVC Network Inc.")
PredicateArgument("it completed its acquisition of CVN Cos. for about $ 423 million .")
PredicateLink(PredicateMention("said"), PredicateArgument("said"))
PredicateLink(PredicateMention("said"), PredicateArgument("QVC Network Inc."))
PredicateLink(PredicateMention("said"), PredicateArgument("it completed its acquisition of CVN Cos. for about $ 423 million ."))
```

* Q4: If Q3 is correct, I use the `PredicateLink` to link predicate with argument. However, you mentioned that I will use `RelationLink` object so where should I use `RelationLink`?

* Q5: Is there any instruction for coding style and document style? I remembered you mentioned that in our meeting, but still not clear the specific resource that I can refer?

**Comment by hunterhector** [comment]
> * Q1: What do you mean by creating a field for this dataset? Could you elaborate a bit more?

I mean if each data entry contains additional fields for a relation, then you may need to edit the ontology to add the field. But it looks like for Open IE we don't need to create additional link types or fields.

> * Q2: The following is one sample row I extracted from the OIE dataset that I found. Just would like to check if the OIE dataset I found is correct?
> 
> ```
> # Format
> [SENTENCE  PREDICATE   ARG1    ARG2    ....]
> # Sample row
> QVC Network Inc. said it completed its acquisition of CVN Cos. for about $ 423 million .    said    said    QVC Network Inc.    it completed its acquisition of CVN Cos. for about $ 423 million .
> ```

This seems to be OK.

> > Read in data as Forte format.
> 
> * Q3: based on the OIE dataset, I probably will create all the following entries for oie reader. Are those correct?
> 
> ```
> Document("<the entire document (all rows like the above in the file)>")
> Sentence("<the entire above sentence>")
> PredicateMention("said")
> PredicateArgument("said")
> PredicateArgument("QVC Network Inc.")
> PredicateArgument("it completed its acquisition of CVN Cos. for about $ 423 million .")
> PredicateLink(PredicateMention("said"), PredicateArgument("said"))
> PredicateLink(PredicateMention("said"), PredicateArgument("QVC Network Inc."))
> PredicateLink(PredicateMention("said"), PredicateArgument("it completed its acquisition of CVN Cos. for about $ 423 million ."))
> ```

This looks correct. Are there any labels to the Predicate links? I am also wondering why "said" is an argument for "said" itself?

> * Q4: If Q3 is correct, I use the `PredicateLink` to link predicate with argument. However, you mentioned that I will use `RelationLink` object so where should I use `RelationLink`?

In this case, it looks like `PredicateLink` is fine. I said `RelationLink` because I thought this dataset looks more like a relation dataset. Sorry for the confusion.

> * Q5: Is there any instruction for coding style and document style? I remembered you mentioned that in our meeting, but still not clear the specific resource that I can refer?
Please read the contribution guideline here: https://github.com/asyml/forte/blob/master/CONTRIBUTING.md


Overall, if you find that the current ontology structure is enough for this dataset, then just go ahead. We only need to create more types if the ontology missed some fields.
