### ISSUE TITLE
Run Through NER Task and Check the result

### ISSUE THREAD

**Issue by Jiaqiang-Ruan** [asyml/forte#249]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Download data and successfully run the task.

**Comment by Jiaqiang-Ruan** [comment]
The code for NER example is a little bit out of date. And I add some lines to make the code runable now.
1. The config is passed to the prepare_pipeline in train_pipeline
2. The resource from prepare_pipeline is return to train_pipleline
3. Fix some config problem for batcher

The output after running one epoch.

`INFO:forte.trainer.ner_trainer:Total number of ner_data: 14987
INFO:forte.trainer.ner_trainer:Average sentence length: 13.650
INFO:forte.trainer.ner_trainer:Train: 200, loss: 5.497
INFO:forte.trainer.ner_trainer:Train: 400, loss: 4.222
INFO:forte.trainer.ner_trainer:Train: 600, loss: 3.707
INFO:forte.trainer.ner_trainer:Train: 800, loss: 3.418
INFO:forte.trainer.ner_trainer:Train: 1000, loss: 3.195
INFO:forte.trainer.ner_trainer:Epoch: 1, steps: 1133, loss: 3.082, time: 617.383s`

**Comment by hunterhector** [comment]
This is nice! I'd suggest we keep these code in a branch, which may come to play in the future (for example, we need to compare the results of the newer interface with this one).
