### ISSUE TITLE
No not safeguard against wrong data type in attributes

### ISSUE THREAD

**Issue by hunterhector** [asyml/forte#434]
**Is your feature request related to a problem? Please describe.**
Due to Python's duck-typing, the system cannot safeguard assignments to the attribute of an entry. This means one can assign complex objects to any attribute. For example, one can assign an object to a string attribute. This creates several problems. First, many downstream systems may break, or some Forte processor that assumes the typing will break. Second, after serialization, we use "jsonpickle", which will still serialize the class but will make the deserialization part depending on this particular class. Third, it may further create security threats.

**Describe the solution you'd like**
The system should safeguard the types of the system at some point, to fail at runtime if user assign an incompatible type.

**Describe alternatives you've considered**

**Additional context**

**Comment by hunterhector** [comment]
We should only consider limited and efficient safe-guard methods. Otherwise we should probably clost this issue with `won't fix`

**Comment by J007X** [comment]
Yes I think after discussion the current suggested fixing will not be efficient so it might end up not better than the not-fixed version. Will look at this later when related changes/tech make it more feasible to fix efficiently.
