### ISSUE TITLE
Polish NER example

### ISSUE THREAD

**Issue by gpengzhi** [asyml/forte#46]
Is it possible to have a script that can automatically download and prepare the dataset for the user? If the answer is no, can we have a more detailed description of the data preparation part? I am not very clear about how to prepare the CONLL03 data for this example.

**Comment by AvinashBukkittu** [comment]
I have updated the README on how to access the dataset as part of https://github.com/asyml/forte/pull/81. To get a copy of CONLL03 dataset, one needs to write an email to the author stating the purpose of use. Hence, it is not possible to provide a download link. The README should be good reference to point the user to the right location.
