### ISSUE TITLE
is the crf trainable ?

### ISSUE THREAD

**Issue by seyeeet** [asyml/forte#502]
Hi 
I am looking at the [example about the ner](https://github.com/asyml/forte/tree/master/examples/ner) here and I see that [crf](https://github.com/asyml/forte/blob/e1e83cfd323d3cd330e38375d8c825e501fe30d4/forte/models/ner/conditional_random_field.py#L192) is being used there.
is the crf being trained in the training and then will be used in the testing or it is just not trainable?
the reason is that I am not sure how we should define the mask in the testing time for the crf?

**Comment by hunterhector** [comment]
Hi, 

The code is supposed trainable at the time of writing but we have recently made a lot of updates to the training interface, now that part of the code is not up to date and hard to be trained. 

We are adding new examples to reflect our training interface, but they are still work in progress in this folder: https://github.com/asyml/forte/tree/master/examples/tagging

Sorry about the inconvenience here, but the core content such as the model code structure are still correct.
