### ISSUE TITLE
PlainSentenceTxtgenReader should be updated

### ISSUE THREAD

**Issue by gpengzhi** [asyml/forte#53]
`PlainSentenceTxtgenReader` is currently not executable. For example, [here](https://github.com/hunterhector/forte/blob/master/forte/data/readers/plainsentence_txtgen_reader.py#L52), `Sentence` class requires three arguments, but only two are given.

**Comment by AvinashBukkittu** [comment]
The latest master https://github.com/asyml/forte/tree/466b82018fc9a18e19771e7e0d614a15ea1c2619 has fixed this issue. Closing this issue.
