### ISSUE TITLE
Add a interface to get results from the pipeline without using index

### ISSUE THREAD

**Issue by jzpang** [asyml/forte#546]
**Is your feature request related to a problem? Please describe.**
looks like we don't have a good way to get results from the pipeline except explicitly using the index. 

for example, given a pipeline nlp, containing two components and two evaluators, the pipeline will be
nlp.add(component1)
nlp.add(evaluator1)
nlp.add(component2)
nlp.add(evaluator2)

The way to access the two evaluators and print out the evaluation results is 
nlp.components[-1]
nlp.components[-3]

**Describe the solution you'd like**
For example, we can create an interface `pipeline.get_eval_result("EvaluatorName")`

**Comment by hunterhector** [comment]
We actually don't have a name for each component (only the class path, but that's not unique). So to do this we may need to first allow assigning names to each component.
