### ISSUE TITLE
Infer the input and output data type of pipeline components without executing the pipeline

### ISSUE THREAD

**Issue by zhanyuanucb** [asyml/forte#551]
**Is your feature request related to a problem? Please describe.**
For deploying a pipeline onto some platforms, it may be necessary to reconstruct the pipeline. Knowing the input and output data type (e.g. DataPack v.s. MultiPack) of each pipeline component without executing the whole pipeline will be helpful for this pipeline reconstruction.

**Describe the solution you'd like**
So far, readers determine the initial input type in the pipeline and casters are the only components that can change the data type. Therefore, one solution can be adding static and abstract methods in some base classes of readers and casters to retrieve the data types of their input and output.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by zhanyuanucb** [comment]
Notice that `BaseReader` has property `pack_type` [here](https://github.com/asyml/forte/blob/master/forte/data/base_reader.py#L109-L111), and `PackReader` and `MultiPackReader` implement this property: [here](https://github.com/asyml/forte/blob/master/forte/data/base_reader.py#L383-L385) and [here](https://github.com/asyml/forte/blob/master/forte/data/base_reader.py#L383-L385).

Would it be a good idea to have `Caster` follow this pattern?

**Comment by hunterhector** [comment]
oh, interesting. I forgot that we actually have the property for readers. It sounds like a good idea to use the same pattern

**Comment by zhanyuanucb** [comment]
But these properties need to be static.

**Comment by hunterhector** [comment]
you are right. In fact, the `pack_type` properties should be safe to convert to static because we don't have any instance method that can change this property. All we need to do is to add `static` annotation to these functions

**Comment by zhanyuanucb** [comment]
I guess it doesn't quite make sense to use both `@property`  and `@staticmethod` in python at the same time because property requires instantiation?
Should we use `@staticmethod` only?

**Comment by hunterhector** [comment]
Did it throw an exception? If that's the case, I think it is find to make it static only, but make sure to check the usage of the function to make sure they uses them as function call instead of variable reference (i.e. pack_type() instead of pack_type)

**Comment by zhanyuanucb** [comment]
Sounds good. I'll make sure to check all the usage. 
Using `@property` and `@staticmethod` at the same time is tricky because using the decorator `@property`:
```
class MyClass:
    @property
    def x(self):
        return "x"
```
is equivalent to 
```
class MyClass:
    def get_x(self):
        return "x"
    x = property(get_x)
```

So a _static property_ `MyClass.x` in this way is expected to be a `property` object. 
Plus, adding a `@staticmethod` above `@property` and calling `MyClass.x()` will throw an error saying `TypeError: 'property' object is not callable`.
