### ISSUE TITLE
incompatible issue with forte.nltk

### ISSUE THREAD

**Issue by wanglec** [asyml/forte#565]
**Describe the bug**
The package name is changed to fortex.nltk. Examples which contain "import forte.nltk" need to be changed to fortex.nltk.

**To Reproduce**
1. Run any example includes "import forte.nltk"
2. See error

**Expected behavior**
The import process should have no error.

**Screenshots**

**Environment (please complete the following information):**
 - Python and Package verions: [e.g. Python version, Pytorch version]

**Additional context**

**Comment by Xuezhi-Liang** [comment]
Now I am looking into this issue and now preparing to fix it.____Xuezhi Liang(MBZUAI)

**Comment by hunterhector** [comment]
@Xuezhi-Liang hi, another teammate of us has been assigned on this one a couple of days ago, I will update the "assignee" to clarify this. Sorry about this.

**Comment by Xuezhi-Liang** [comment]
@hunterhector, It's Ok. Got it.
