### ISSUE TITLE
Add metric ontology

### ISSUE THREAD

**Issue by zhanyuanucb** [asyml/forte#566]
**Is your feature request related to a problem? Please describe.**
In some tasks like training, tuning, or validation, we need components to report metrics so that we can gauge their performance.

**Describe the solution you'd like**
Define metric ontology so that components can report metrics in output DataPack(s). More specifically, define:
- `SingleMetric` represents metrics containing a single number. For example, accuracy, loss...
- `NdMetric` represents metrics that are N-d arrays. For example, cross-validation scores (1-d array), confusion matrix (2-d array)...

**Describe alternatives you've considered**

**Additional context**
The current ontology generator couldn't add `ndarray` attribute to an ontology. Need to create another issue for this feature.

**Comment by hunterhector** [comment]
Let's start assigning owners to the issues since there is another team that working to pick issues from our repo.
