### ISSUE TITLE
Add a new annotation in DataStore

### ISSUE THREAD

**Issue by qinzzz** [asyml/forte#594]
**Is your feature request related to a problem? Please describe.**
Implement `add_annotation_raw(self, type_id: int, begin: int, end: int ) -> Tuple[int, int]` in data_store.py

The new DataStore class needs an API to add a new annotation, with given type, begin ,and end arguments.
This function should store the new entry in this class, and return the tid and index for the entry.

**Depends on**
pull request #586

**Describe the solution you'd like**
We should create the `entry data` as a list, with the format [begin, end, tid, entry_type, attr_1, ..., attr_n].
Attr_1 to attr_n are attributes for this type and are different for each type. They are initialized as None value.
A helper function _new_annotation() can be used to generate a new annotation type entry data with default fields.

A reference to the entry should be store in both self.elements and self.entry_dict.

**Describe alternatives you've considered**

**Additional context**
- This is part of the data efficiency project
- This PR should be made to the `master` branch.
- After the data tuple class is finished, we may switch to a new branch for integration.

**Comment by wanglec** [comment]
I think I create the same issue by mistake and that one is taken by betermj. Close this now.
