### ISSUE TITLE
After deserializing from serialized complex objects containing a dictionary (such as MultiPack that uses '_inverse_pack_ref') the KEY of the dictionary becomes string (from previous int for example)

### ISSUE THREAD

**Issue by J007X** [asyml/forte#595]
**Describe the bug**
After deserializing from serialized complex objects containing a dictionary (such as MultiPack that uses '_inverse_pack_ref') the KEY of the dictionary becomes string (from previous int for example). For example in  MultiPack. the dict '_inverse_pack_ref' 
should be [int, int] but after deserialization (by JSONPickle) it becomes [str, int] and any attempt to using an int (such as pack_id) as key to lookup in such dictionary will generate an KeyError exception instead of the correct result, so currently this can only be workaround as the following addtional string conversion and catch additional errors (which is not ideal):

    def get_pack_index(self, pack_id: int) -> int:
        try:
            return self._inverse_pack_ref[pack_id]
        except KeyError:  # sometimes after deserialization the dict have string as key
            s_dict: dict = self._inverse_pack_ref
            s_key = str(pack_id)
            try:
                return s_dict[s_key]
            except KeyError as ke:  # really not found
                raise ProcessExecutionException(
                    f"Pack {pack_id} is not in this multi-pack."
                ) from ke

**To Reproduce**
the 2 test cases of MultiEntryStructure in entry_data_structures_test.py can be used.
Basically serialize a MultiPack with at least 2 data_packs in it to a string , then deserialize from the string, and re-link the data_packs. This will generate an exception with the new changes that refer/accessing the data_packs in a multi-pack by pack_id instead of by internal array index (#559 related enhancements). So an old version of "get_pack_index" in multi-pack not handling the int -> str change of the dictionary will fail to lookup for the pack correctly.

**Expected behavior**
Such dictionary will be unchanged after deserialization

**Screenshots**

**Environment (please complete the following information):**
(non-specific)

**Additional context**
Per discussion with Hector, this seems to relate to the following discussion (when serialized to JSON):
https://stackoverflow.com/questions/1450957/pythons-json-module-converts-int-dictionary-keys-to-strings

**Comment by hunterhector** [comment]
As a note, this issue will not be fixed by https://github.com/asyml/forte/pull/576, in 576, a work-around is proposed but it does not solve the problem entirely.
