### ISSUE TITLE
Set entry attribute in DataStore 

### ISSUE THREAD

**Issue by qinzzz** [asyml/forte#596]
**Is your feature request related to a problem? Please describe.**
Implement `set_attr(self, tid: int, attr_id: int, attr_value)` in forte/forte/data/data_store.py.
This function locates the entry data with `tid` and sets its attribute `attr_id` with value `attr_value`.
Unit tests are in forte/tests/forte/data/data_store_test.py.

**Depends on**
pull request #586 

**Describe the solution you'd like**
We first retrieve the entry data from entry_dict using tid. 
We then locate the attribute using attribute id, and update the attribute with given value `attr_value`.

**Describe alternatives you've considered**

**Additional context**
- This is part of the data efficiency project
- This PR should be made to the `master` branch.
- After the data tuple class is finished, we may switch to a new branch for integration.

**Comment by wanglec** [comment]
closed by pull request #608
