### ISSUE TITLE
set_fields should be replaced by explicit setters

### ISSUE THREAD

**Issue by hunterhector** [asyml/forte#61]
Currently, all fields in the ontology are set via ``set_fields`` method. This should not be used externally since it will allow the user to add any field to the ontology. We should instead allow the code-gen to add explicit setters for each attribute.

**Comment by hunterhector** [comment]
@mgupta1410 We need to take action to convert the current ontology to generated ones, the longer we wait the more work we will have on this.

**Comment by mgupta1410** [comment]
This is done, closing @hunterhector.
