### ISSUE TITLE
clinical pipeline error

### ISSUE THREAD

**Issue by tanyuqian** [asyml/forte#622]
**Describe the bug**
The [clinical pipeline example](https://github.com/asyml/forte/blob/master/examples/clinical_pipeline/) runs into an error. 

**To Reproduce**
Firstly, update Line7-9 of [clinical_processing_pipeline.py](https://github.com/asyml/forte/blob/master/examples/clinical_pipeline/clinical_processing_pipeline.py) into
```python
from fortex.elastic import ElasticSearchPackIndexProcessor
from fortex.huggingface.bio_ner_predictor import BioBERTNERPredictor
from fortex.huggingface.transformers_processor import BERTTokenizer
```
After installing dependencies and downloading models, an error occurs when running the pipeline, as the screenshot shows
![forte_issue](https://user-images.githubusercontent.com/18486816/152466394-bf3fdaea-34c8-40cc-afdb-b51801d7880e.png)

**Environment (please complete the following information):**
 - OS:Ubuntu 20.04
 - Python and Package verions: Python 3.8.8, Pytorch 1.10.0

**Comment by Piyush13y** [comment]
After trying to run a few examples, this error seems to be happening whenever `BioBERTNERPredictor()` is added to the pipeline. Commenting out this component from the pipeline, doesn't show the error anymore. Has to do with some flow with this component.

**Comment by hunterhector** [comment]
@Piyush13y @feipenghe is working on this issue actively.

**Comment by Piyush13y** [comment]
Yes, I was working with the example codes, to get the medicine demo pipeline running. Thought I would just share the insight.

**Comment by hunterhector** [comment]
> Yes, I was working with the example codes, to get the medicine demo pipeline running. Thought I would just share the insight.

You can skip using this particular `BioBERTNERPredictor` since the task is more like getting familiar with Forte and know how to work with processors. For example, you can try using the spacy one (https://github.com/asyml/forte-wrappers/blob/main/src/spacy/fortex/spacy/spacy_processors.py#L325), which also has some medical prediction components.
