### ISSUE TITLE
Texer numpy version requirement is outdated

### ISSUE THREAD

**Issue by feipenghe** [asyml/forte#634]
**Describe the bug**
Recent developments shows that numpy version requirement <1.19 is outdated, and it causes incompatibility with recent tensorflow versions and potentially other packages in the future.

**To Reproduce**
No particular way to reproduce.

**Expected behavior**
It's expected `texar` numpy version is updated to be compatible with numpy>1.21 

**Screenshots**

**Environment (please complete the following information):**
 - Python and Package verions: [e.g. Python version, Pytorch version]

**Additional context**
An example issue occured in the git runner is here https://github.com/asyml/forte-wrappers/runs/5120444152?check_suite_focus=true#step:8:83

According to @hunterhector , 
> About the Numpy issue,  it is restricted here https://github.com/asyml/texar-pytorch/blob/master/requirements.txt#L3 
Previously I restricted this to 1.19.5 since there will be CI errors. I remember that’s due to mypy checks since Numpy introduce its own typing since 1.20 (before that we are using generated stubs). So without this 1.19.5 limit, it will raise a lot of linting errors. Now this restriction is a bit too strict and will be outdated soon.

**Comment by hunterhector** [comment]
This PR https://github.com/asyml/texar-pytorch/pull/352 has solved the problem, can we update the versions on TensorFlow now?

**Comment by feipenghe** [comment]
This issue has been fixed.
