### ISSUE TITLE
Documentation for DataPackDataset is outdated

### ISSUE THREAD

**Issue by feipenghe** [asyml/forte#667]
**Describe the bug**
Documentation for `DataPackDataset` is outdated.
There is no [feature_resource](https://github.com/asyml/forte/blob/ae3d46884c26bac95893cbbecfaf86168a039bdc/forte/data/data_pack_dataset.py#L153) method. 

**To Reproduce**
1. Prepare data `...`
2. Run command '....'
3. See error

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Python and Package verions: [e.g. Python version, Pytorch version]

**Additional context**

**Comment by hunterhector** [comment]
You can refer to documentation here: https://github.com/asyml/forte/blob/master/forte/train_preprocessor.py#L263
