### ISSUE TITLE
Documentation for BaseElasticSearchDataSelector is outdated 

### ISSUE THREAD

**Issue by feipenghe** [asyml/forte#669]
**Describe the bug**
In the [documentation](https://github.com/asyml/forte/blob/ae3d46884c26bac95893cbbecfaf86168a039bdc/forte/processors/base/data_selector_for_da.py#L47), `forte.indexers.elastic_indexer.ElasticSearchIndexer` doesn't exist. The class `ElasticSearchIndexer` is not found in the repo.

**To Reproduce**
1. Prepare data `...`
2. Run command '....'
3. See error

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Python and Package verions: [e.g. Python version, Pytorch version]

**Additional context**

**Comment by hunterhector** [comment]
The class is now here: https://github.com/asyml/forte-wrappers/blob/main/src/elastic/fortex/elastic/elastic_indexer.py#L33
