### ISSUE TITLE
ModuleNotFoundError: No module named 'fortex.elastic'   #701

### ISSUE THREAD

**Issue by bhaskar2443053** [asyml/forte#701]
**Describe the bug**
example/clinical pipeline shows No module named 'fortex.elastic' 

**To Reproduce**
1. Prepare data `...`
2. Run command '....'
python clinical_processing_pipeline.py /path/to/mimiciii/1.4/NOTEEVENTS.csv.gz /path_to_sample_output 10000

(forte) bhaskarrao@LM00824BRAO clinical_pipeline % python clinical_processing_pipeline.py /path/to/mimiciii/1.4/NOTEEVENTS.csv.gz /path_to_sample_output 10000
Traceback (most recent call last):
  File "/Users/bhaskarrao/Documents/forte/examples/clinical_pipeline/clinical_processing_pipeline.py", line 12, in <module>
    from fortex.elastic import ElasticSearchPackIndexProcessor
ModuleNotFoundError: No module named 'fortex.elastic'

**Expected behavior**

**Screenshots**

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/17160282/160075001-e818c55f-6406-49c9-8f9c-572d9b54c263.png">

**Environment (please complete the following information):**
 - OS: [e.g. iOS] mac
 - Python and Package verions: [e.g. Python version, Pytorch version]

**Additional context**

**Comment by feipenghe** [comment]
Have you follow steps from https://github.com/asyml/forte-wrappers to install `elastic`?

**Comment by bhaskar2443053** [comment]
error resolved. I had some installation issue. after reinstalling the error vanished.
