### ISSUE TITLE
twitter sentiment example

### ISSUE THREAD

**Issue by bhaskar2443053** [asyml/forte#716]
**Describe the bug**
the twitter api authentication is modified now, so tweepy api call needs to be modified accordingly.
**To Reproduce**

python pipeline.py

**Expected behavior**

**Screenshots**
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/17160282/161005977-6ef478ad-087b-4736-988c-f8ff1e92662e.png">
**Environment (please complete the following information):**
 - OS: [e.g. iOS] linux
 - Python and Package verions: [e.g. Python version, Pytorch version]

**Additional context**

**Comment by hunterhector** [comment]
thanks, @bhaskar2443053 could you help resolve the issue?

**Comment by bhaskar2443053** [comment]
sure, I ll work on it.
I might have few questions though !
