### ISSUE TITLE
Support cache for `_is_annotation`

### ISSUE THREAD

**Issue by wanglec** [asyml/forte#743]
**Is your feature request related to a problem? Please describe.**
We want to add the cache functionality for the function `_is_annotation`. It should remember whether the entry is annotated-like once it has been checked.

**Depends on**
- List issues that this one depends on.

**Describe the solution you'd like**
We may use a lru decorator to cache the return value of this function.

**Describe alternatives you've considered**

**Additional context**
- This is part of the data efficiency project
- This PR should be made to the `master` branch.
- After the data tuple class is finished, we may switch to a new branch for integration.

**Comment by hunterhector** [comment]
@mylibrar double check to see if this is addressed, or assign a milestone

**Comment by hunterhector** [comment]
addressed in another pr.
