### ISSUE TITLE
Putting audio data into Datapack in Javascript For Remote Forte Processing

### ISSUE THREAD

**Issue by OscarSong2003** [asyml/forte#757]
**Describe the question**
A clear and concise description of what your question is, which concept or procedure is unclear to you?

I am wondering if there is a way to create a forte DataPack in Javascript/Typescript (as a part of a new stave audio recorder plugin) and populate it with audio data (in the form of audio blob). I saw on the documentation that audio DataPacks can be initialized in python (with audio as numpy array), but for my purpose I am unsure how I can get around this as the plugin is developed in Javascript.   

**What you want to do**
Sometimes there might be alternative way to solve your problem, consider telling us what you want to do.

I am developing an audio analyzer, where a stave plugin will record a user's voice, and then save the audio in the form of a datapack which would be sent to forte for remote processing. I have developed both a pipeline as well as a front end recorder, but need to be able create an empty datapack and populate it with audio data (in the plugin written in Typescript and React before sending it to forte to process. 

**Additional context**
Add any other context about the problem here, such as versions, screenshots
N/A

**Comment by mylibrar** [comment]
Right now I don't think `stave` can support this directly from the frontend utilities. I would recommend registering a new backend handler to populate DataPack with audio data. You might need to know some basics of `Django` and `react.js`. Here is a rough guide for it:
* Add a new handler in https://github.com/asyml/stave/blob/master/simple-backend/stave_backend/handlers/document.py
* Register an URL path for your handler in https://github.com/asyml/stave/blob/master/simple-backend/stave_backend/urls.py
* Create a function in frontend to call this API https://github.com/asyml/stave/blob/master/src/app/lib/api.ts

You can design the interface of this new backend function and determine how it interacts with frontend.

**Comment by OscarSong2003** [comment]
Thank you for your suggestions!
