### ISSUE TITLE
Check duplicates when adding entries to DataStore

### ISSUE THREAD

**Issue by mylibrar** [asyml/forte#774]
**Is your feature request related to a problem? Please describe.**
In [`DataPack.__add_entry_with_check`](https://github.com/asyml/forte/blob/master/forte/data/data_pack.py#L635), we provide an option called `allow_duplicate` to specify whether to add identical entries into `DataPack`. If it's set to `False`, then `__add_entry_with_check` should just return the existing entry if a duplicate is found. To keep the old API interfaces, we should also add this option in `DataStore`.

**Describe the solution you'd like**
We can refer to the current [implementation](https://github.com/asyml/forte/blob/master/forte/data/data_pack.py#L692) in `DataPack` and migrate it to `DataStore`. For example, we can add some checking [here](https://github.com/asyml/forte/blob/master/forte/data/data_store.py#L449) before adding a new annotation.

**Describe alternatives you've considered**
If duplicate entries are allowed, we should be careful of any functions involved with binary searching since the results might not be unique. For example, in `DataStore.get_entry_index`, the [index](https://github.com/asyml/forte/blob/master/forte/data/data_store.py#L694) returned by `bisect_left` might not be the exact entry we expect to find.

**Additional context**
This should be merged to `master` branch.

**Comment by feipenghe** [comment]
Does duplicates means tid and entry's list representation are all the same?
If so, `DataStore.get_entry_index` can still get the leftmost index of duplicate entries which is still reasonable.
For example, if we have [entry_a, entry_b, entry_b, entry_b], `get_entry_index(entry_b)` returns `1`.

**Comment by hunterhector** [comment]
The duplicate definition depends on the equality check of the particular entry. For example, for an Annotation, `__eq__` is defined here https://github.com/asyml/forte/blob/master/forte/data/ontology/top.py#L105, which only means the type (e.g. Token) and span.

**Comment by hunterhector** [comment]
Tbh, it does make sense to add comparison functions with data store implementation, including `__eq__`, `__lt__`, `__hash__` @mylibrar, any thoughts here? where should they be?

**Comment by mylibrar** [comment]
> Tbh, it does make sense to add comparison functions with data store implementation, including `__eq__`, `__lt__`, `__hash__` @mylibrar, any thoughts here? where should they be?

One idea is to use [SortedList(key=comparison_func)](https://github.com/asyml/forte/blob/master/forte/data/data_store.py#L451). Right now we only implement this in [add_annotation_raw()](https://github.com/asyml/forte/blob/master/forte/data/data_store.py#L428), which uses `[begin, end]` as comparison key.
