### ISSUE TITLE
Add a new optional argument `tid` in `DataStore.add_entries` 

### ISSUE THREAD

**Issue by mylibrar** [asyml/forte#775]
**Is your feature request related to a problem? Please describe.**
We want to provide an option called `tid` in `DataPack` when adding new entries (e.g., `add_annotation_raw`, `add_link_raw`, etc.). This is mainly for backward compatibility when integrating `DataStore` to `DataPack`. Right now `DataStore` creates a new random `tid` when adding an entry, but in many cases we would also like to insert an existing entry object that has already been assigned with a `tid`.

**Describe the solution you'd like**
Provide a new optional argument `tid` in `DataStore.add_entries`. Below is a tentative implementation for `_new_link()`:
```python
def _new_link(self, type_name: str, parent_tid: int, child_tid: int, tid: Optional[int] = None) -> List:
    tid: int = self._new_tid() if tid is None else tid
    ...
```
We can make the same updates to `_new_annotation()`, `_new_group()`, etc.

**Additional context**
This updates should be merged to `master` branch.

**Comment by feipenghe** [comment]
If `tid` is given in method, is there any check needed?

**Comment by mylibrar** [comment]
Yes I think there should be some validity checking.

**Comment by feipenghe** [comment]
If `tid` is given, it must be existing `tid` that in `self.__entry_dict.keys()`. Right?

**Comment by mylibrar** [comment]
> If `tid` is given, it must be existing `tid` that in `self.__entry_dict.keys()`. Right?

The input can be a new entry that has not been added to `DataStore` yet, so `tid` doesn't have to be an existing one in `__entry_dict`.

**Comment by mylibrar** [comment]
> `add_link_raw` and `add_group_raw` methods such as [here](https://github.com/asyml/forte/blob/5ab4c2bb11011a9f05e3c9d427106d02f372b99f/forte/data/data_store.py#L457) are not implemented yet. Should I implement it in this PR?

There are two other issues for them (#629, #630). I guess you don't need to fix all of them in this PR, but you still can update the function signature for `add_link_raw` and `add_group_raw`.

**Comment by hunterhector** [comment]
yeah I also ask other members, these tasks are not taken yet
