### ISSUE TITLE
Develop a reader for multiple-choice QA dataset

### ISSUE THREAD

**Issue by hunterhector** [asyml/forte#80]
This issue is to add readers (https://github.com/asyml/forte/tree/master/forte/data/readers) for multiple-choice QA datasets, such as [RACE](http://www.cs.cmu.edu/~glai1/data/race/). The tasks involve:

1. Define an ontology for Multiple-choice QA
1. Create a reader that read the text from a dataset
1. Create annotations for each question and choice, including the labels

Extra requirements:
1. There could be a general version that contains the main logic, which can be extended to cope with different datasets.

**Comment by atif93** [comment]
Should we close this? @hunterhector

**Comment by hunterhector** [comment]
Yes, thank you. Solved in https://github.com/asyml/forte/pull/85
