### ISSUE TITLE
New Grid Ontology Design

### ISSUE THREAD

**Issue by hepengfe** [asyml/forte#817]
**Describe the bug**
Currently we have `Girds` which is holding CV grid. Initially we want the grid class to hold all grid configuration but it's actually not necessary.
* rename `Grids` -> `Grid`
* create a default grid for bounding box beforehand so that it doesn't create a grid in `BoundingBox.__init__`

**To Reproduce**
1. Prepare data `...`
2. Run command '....'
3. See error

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Python and Package verions: [e.g. Python version, Pytorch version]

**Additional context**

**Comment by hepengfe** [comment]
@hunterhector I kinda forgot your idea of creating a default grid for `BoundingBox`. 
Do we create a default grid in `BoundingBox.__init__()` and users need to manually set it later?

**Comment by hunterhector** [comment]
The idea I suggested is to create a default grid whenever necessary, but the creation time might not be related to only `BoundingBox`, it should be anything that requires a grid. Some potential solutions are listed below:

1. Create the default grid when creating the image-related payload, and associate the default grid with the payload.
2. Create an `add_or_get_default_grid` function to the image Payload class, but don't create the grid right away. When any other class like `BoundingBox` require the grid, but the user doesn't provide the grid, we can call the `add_or_get_default_grid` function, which will always return a grid (and create one if called the first time).

I don't have a specific reason for which one is better, but the things to consider are:
1. when we create the grids automatically, will the user becomes confused? For example, the default grid shouldn't intervene or overwrite anything a user creates, and vice versa, if the user creates a grid but does not attempt to change the default grid, we shouldn't change the default grid.
2. when to create the default grid, and how can a user change the grid if one wants to?
