### ISSUE TITLE
Add test cases for MT notebook tutorial

### ISSUE THREAD

**Issue by hunterhector** [asyml/forte#820]
**Is your feature request related to a problem? Please describe.**
We should add basic test cases of the notebooks here: https://github.com/asyml/forte/tree/master/tests/forte/notebooks

Recently we've added a new PR here: https://github.com/asyml/forte/pull/818/ and the test cases should be added to make sure they can be run in the future.

**Describe the solution you'd like**
1. Test basic blocks in the notebook
2. Skip the ones that use online APIs
3. May need to simulate user input to the `input` blocks

**Describe alternatives you've considered**

**Additional context**

**Comment by hepengfe** [comment]
https://github.com/asyml/forte/pull/826
