### ISSUE TITLE
Area for Region ontology

### ISSUE THREAD

**Issue by hepengfe** [asyml/forte#863]
**Describe the bug**
Current region doesn't have area function that computes area of the represented partial image. 

**To Reproduce**
1. Prepare data `...`
2. Run command '....'
3. See error

**Expected behavior**
We want a property function that computes the area of the represented partial image. 

**Screenshots**

**Environment (please complete the following information):**
 - Python and Package verions: [e.g. Python version, Pytorch version]

**Additional context**

**Comment by hunterhector** [comment]
feature template

**Comment by hepengfe** [comment]
https://github.com/asyml/forte/issues/869
