### ISSUE TITLE
`ImagePayload.cache` should support more data type

### ISSUE THREAD

**Issue by hepengfe** [asyml/forte#864]
**Describe the bug**
Currently `ImagePayload.cache` is expected to be `numpy.Ndarray` only, we should support more data types such as some image data objects from `PIL` library.

Also, note that this library supports lazy loading internally while initializing an image object by `PIL.Image.open(image_path)`

**To Reproduce**
1. Prepare data `...`
2. Run command '....'
3. See error

**Expected behavior**
We should have a tutorial for a CV task

**Screenshots**

**Environment (please complete the following information):**
 - Python and Package verions: [e.g. Python version, Pytorch version]

**Additional context**

**Comment by hunterhector** [comment]
We should use the feature request template for this

**Comment by hepengfe** [comment]
https://github.com/asyml/forte/issues/868
