### ISSUE TITLE
OCR example tutorial

### ISSUE THREAD

**Issue by hepengfe** [asyml/forte#865]
**Describe the bug**
We want to have a notebook tutorial for OCR to show forte's capability on managing related data such as images containing text and recognized text, texts' bounding boxes and their relations..

**To Reproduce**
1. Prepare data `...`
2. Run command '....'
3. See error

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Python and Package verions: [e.g. Python version, Pytorch version]

**Additional context**

**Comment by hunterhector** [comment]
Let's use the correct issue template. And let's make sure we fill in the questions of the template
