### ISSUE TITLE
`DataPack` function to add audio and text payload

### ISSUE THREAD

**Issue by hepengfe** [asyml/forte#895]
**Is your feature request related to a problem? Please describe.**
Currently we don't have functions to add new `AudioPayload` and `TextPayload`.

**Describe the solution you'd like**
* `DataPack.add_audio()` that takes audio data and add new `AudioPayload` containing the audio.
* `DataPack.add_text()` that takes text data and add new `TextPayload` containing the text.

**Describe alternatives you've considered**

**Additional context**

**Comment by mylibrar** [comment]
https://github.com/asyml/forte/pull/891#discussion_r942677425
