### ISSUE TITLE
Move MicrosoftBingTranslator into examples/

### ISSUE THREAD

**Issue by AvinashBukkittu** [asyml/forte#90]
Currently we provide `MicrosoftBingTranslator` as a processor in Forte core. It can instead be moved into `examples/` which would demonstrate how to write processors using 3rd party APIs. The machine translation processor can be provided through a texar model.

**Comment by hunterhector** [comment]
Good idea. I think the examples folder can be converted into a package itself, so the different examples actually can cross-reference each other.

**Comment by hunterhector** [comment]
Let's do this type of issue in batch some time.
